apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-medical-ui
  labels:
    app: web-medical-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-medical-ui
  template:
    metadata:
      labels:
        app: web-medical-ui
    spec:
      containers:
        - name: web-medical-ui
          image: dgfc45/web-medical-ui:latest   # यह workflow से dynamically बदलेगा
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-medical-ui-service
spec:
  selector:
    app: web-medical-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
